from datetime import datetime
from typing import Optional

from sqlalchemy import Column, Integer, String, Float, DateTime, Text, JSON, ForeignKey
from sqlalchemy.orm import relationship

from pims.database.core import Base

class Company(Base):
    """
    Represents a company / stock ticker.
    """
    __tablename__ = "companies"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    sector = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    financials = relationship("FinancialData", back_populates="company")
    market_data = relationship("MarketData", back_populates="company")
    research = relationship("Research", back_populates="company")


class FinancialData(Base):
    """
    Financial metrics and fundamental data for a company.
    """
    __tablename__ = "financial_data"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)

    # Financial metrics calculated by Quant Engine
    per = Column(Float, nullable=True)
    pbr = Column(Float, nullable=True)
    roe = Column(Float, nullable=True)
    roic = Column(Float, nullable=True)
    fcf = Column(Float, nullable=True)

    # Metadata for tracking origin
    source = Column(String, nullable=False)
    source_type = Column(String, nullable=False)
    retrieved_at = Column(DateTime, default=datetime.utcnow)
    effective_date = Column(DateTime, nullable=False)
    data_period = Column(String, nullable=True)
    confidence = Column(Float, nullable=True)

    company = relationship("Company", back_populates="financials")


class MarketData(Base):
    """
    Price and market data for a company.
    """
    __tablename__ = "market_data"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)

    current_price = Column(Float, nullable=False)
    volume = Column(Integer, nullable=True)
    market_cap = Column(Float, nullable=True)

    source = Column(String, nullable=False)
    source_type = Column(String, nullable=False)
    retrieved_at = Column(DateTime, default=datetime.utcnow)

    company = relationship("Company", back_populates="market_data")


class Research(Base):
    """
    Stores research and investment theses generated by Research/CIO Agents.
    """
    __tablename__ = "research"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)

    # Structured analysis
    facts = Column(JSON, nullable=False) # List of strings
    interpretations = Column(JSON, nullable=False)
    hypotheses = Column(JSON, nullable=False)
    unknowns = Column(JSON, nullable=False)

    # As identified in the architecture review feedback: store raw response separately
    raw_response = Column(Text, nullable=True)

    source = Column(String, nullable=False)
    retrieved_at = Column(DateTime, default=datetime.utcnow)
    confidence = Column(Float, nullable=True)

    company = relationship("Company", back_populates="research")


class Valuation(Base):
    """
    Stores qualitative valuation interpretations generated by the Valuation Agent.
    """
    __tablename__ = "valuations"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)

    # The calculated financial metrics at the time of valuation
    per = Column(Float, nullable=True)
    pbr = Column(Float, nullable=True)
    roe = Column(Float, nullable=True)
    current_price = Column(Float, nullable=True)

    # Structured qualitative LLM analysis
    is_undervalued = Column(String, nullable=False) # "Yes", "No", "Neutral"
    historical_context = Column(Text, nullable=True)
    peer_context = Column(Text, nullable=True)
    market_expectations = Column(Text, nullable=True)

    raw_response = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    company = relationship("Company")


class Decision(Base):
    """
    Stores the final investment recommendation generated by the CIO Agent.
    """
    __tablename__ = "decisions"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False)

    # CIO Output structured data
    decision = Column(String, nullable=False) # BUY, HOLD, WATCH, etc.
    confidence = Column(Float, nullable=False)

    investment_thesis = Column(JSON, nullable=True)
    evidence = Column(JSON, nullable=True)
    counter_evidence = Column(JSON, nullable=True)

    fair_value = Column(Float, nullable=True)
    expected_return = Column(Float, nullable=True)
    downside = Column(Float, nullable=True)

    recommended_weight = Column(Float, nullable=True)
    recommended_quantity = Column(Integer, nullable=True)

    # Context arrays
    entry_conditions = Column(JSON, nullable=True)
    exit_conditions = Column(JSON, nullable=True)
    monitoring_conditions = Column(JSON, nullable=True)
    unknowns = Column(JSON, nullable=True)
    sources = Column(JSON, nullable=True)

    raw_response = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    company = relationship("Company")


class TradePlan(Base):
    """
    Order plans generated by the Trade Planner/CIO.
    Execution is performed by a human.
    """
    __tablename__ = "trade_plans"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String, nullable=False)
    decision = Column(String, nullable=False) # BUY, HOLD, SELL, etc.
    recommended_weight = Column(Float, nullable=True)
    recommended_quantity = Column(Integer, nullable=True)
    entry_range = Column(String, nullable=True)
    preferred_order_type = Column(String, nullable=True)
    reason = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    status = Column(String, default="PENDING") # PENDING, EXECUTED, CANCELLED


class ExecutionResult(Base):
    """
    Execution results entered by human after trading at a brokerage.
    """
    __tablename__ = "execution_results"

    id = Column(Integer, primary_key=True, index=True)
    trade_plan_id = Column(Integer, ForeignKey("trade_plans.id"), nullable=False)

    executed = Column(String, nullable=False) # True/False stored as string/bool depending on DB
    executed_quantity = Column(Integer, nullable=True)
    executed_price = Column(Float, nullable=True)
    executed_at = Column(DateTime, nullable=True)

    recorded_at = Column(DateTime, default=datetime.utcnow)
    recorded_by = Column(String, default="HUMAN")


class AgentRun(Base):
    """
    Tracking agent execution, model usage, and costs.
    """
    __tablename__ = "agent_runs"

    id = Column(Integer, primary_key=True, index=True)
    agent_name = Column(String, nullable=False)
    model = Column(String, nullable=False)
    input_tokens = Column(Integer, nullable=True)
    output_tokens = Column(Integer, nullable=True)
    estimated_cost = Column(Float, nullable=True)
    latency_ms = Column(Integer, nullable=True)
    tool_calls = Column(Integer, default=0)
    retry_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)


class AuditLog(Base):
    """
    Immutable audit log for all critical decisions and actions.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    agent = Column(String, nullable=False)
    model = Column(String, nullable=True)
    prompt_version = Column(String, nullable=True)
    input_reference = Column(String, nullable=True)
    data_version = Column(String, nullable=True)
    decision = Column(String, nullable=False)
    confidence = Column(Float, nullable=True)
    sources = Column(JSON, nullable=True)
    human_approval = Column(String, nullable=True) # E.g., boolean or status string
